changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
  categories:
    - title: "New Features"
      labels:
        - enhancement
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Internal"
      labels:
        - internal
